### PR TITLE
Fix some issues with initial version and setup for metadata driven feature

### LINKED ISSUE #17: Enable Metadata Driver Configuration for IdPs
To reduce the effort in maintaining IdPs, metadata driven configuration moves some IdP configuration setting from the IdP into metadata. In particular but not limited to settings in the relying-party.xml configuration file. 

To implement will require some experimentation to develop an understanding of how the system functions, setting required and any limitations or potential performance issues. 

First step is to enable metadata driven configuration for SAML 2.0 Browser SSO. This can be achieved by replacing SAML2.SSO bean with SAML2.SSO.MDDriven in the profile Configurations of the Default Relying Party.

Once enabled we can begin experimenting.

### LINKED ISSUE #18: Upgrade logback_classic and slf4j to version to 1.5.6

### LINKED ISSUE #19: Move from ansible to ansible-core with modules
REDHat and OL now provide the latest version ansible through ansilbe-core. They still support a package called ansible but it is either an older version of ansilbe that does not work with the installer (OL) or it is a package that installs ansilbe-core plus many of the packages to make it like the old ansible. 

To be consistent we will remove the ansilbe package and install ansilbe-core and the following three modules:

- ansible.posix
- community.crypto
- community.mysql

The following changes are required and will be applied initially to Fedora like OSs.

- bootstrap-v5.sh
  - Remove ansible
  - Install ansible-core
  - Install modules

### PR DESCRIPTION
**Pull request by trsau**
Resolver #21 
Resolves #19 
Resolves #18 
Resolves #17

### CODE REVIEW

**Review by ArthurZheng — APPROVED** [review]
Good work, Terry!

File: bootstrap-v5.sh [hunk 1]
```diff
@@ -37,6 +37,8 @@ function set_internal_variables {
 
     GIT_REPO=https://github.com/ausaccessfed/shibboleth-idp5-installer.git
     GIT_BRANCH=main
```
Comment (ArthurZheng) [inline bootstrap-v5.sh]: Is this redundant now? As we have a new declaration below:     GIT_BRANCH=feature-metadata-driven

Comment (trsau) [reply bootstrap-v5.sh]: Oops, though I had removed the second one. It needs to be GIT_BRANCH=main.
